Feat(userAuth): 이메일 기능 추가, 유저 Role 부여
OuOHoon/nbc-newsfeed pull request #14
Opened 2023-11-24 11:17 UTC by wkdehdgk159

꼼꼼히 봐주시면 감사하겠습니다.. 문제가 많을테니..

2023-11-25 08:48 UTC, zomeong approved these changes
주석을 꼼꼼히 달아주셔서 코드 보기가 편했어요 코드도 아주 깔끔하고 좋습니다 고생하셨습니다👍

2023-11-26 06:53 UTC, OuOHoon requested changes
변경사항이 많네요 ㅎㅎ 고생하셨습니다~!!

2023-11-26 06:53 UTC, OuOHoon commented on src/main/java/com/sparta/newsfeed/user/dto/MailAuthRequestDto.java
> +    @NotNull
생성되는 authcode의 자릿수를 지정해주는건 어떨까요 ㅎㅎ

2023-11-26 06:53 UTC, OuOHoon commented on src/main/java/com/sparta/newsfeed/user/AuthCode.java
> +    private String username;
혹시 User와의 연관관계가 아니라 username인 이유가 있을까요?(궁금) username도 unique 하니까 key로 사용 가능해서 기능에는 문제 없을 것 같은데 이유가 있는지 궁금하네요 ㅎㅎ

2023-11-26 06:53 UTC, OuOHoon commented on src/main/java/com/sparta/newsfeed/user/AuthCode.java
> +    private final LocalDateTime createdAt = LocalDateTime.now();
jpa auditing을 사용하면 자동으로 생성일자를 넣어줄 수 있다고 합니다 ㅎㅎ

2023-11-26 06:53 UTC, OuOHoon commented on src/main/java/com/sparta/newsfeed/user/UserRoleEnum.java
> +    GUEST(Authority.GUEST);  // 관리자 권한
관리자 권한 주석은 실수하신 것 같습니다 ㅋㅋㅋㅋ

2023-11-26 07:03 UTC, Youkamii commented on src/main/java/com/sparta/newsfeed/user/UserService.java
> +        return generator.nextInt(1000000) % 1000000;
6자리를 이런식으로 생성하는 하는군요

2023-11-26 07:08 UTC, wkdehdgk159 commented on src/main/java/com/sparta/newsfeed/user/dto/MailAuthRequestDto.java
> +    @NotNull
넵 바로 반영드가겠습니다

2023-11-26 07:10 UTC, wkdehdgk159 commented on src/main/java/com/sparta/newsfeed/user/UserRoleEnum.java
> +    GUEST(Authority.GUEST);  // 관리자 권한
코드 복붙이 이렇게 들통나네요 ㅠ

2023-11-26 07:11 UTC, wkdehdgk159 commented on src/main/java/com/sparta/newsfeed/user/UserService.java
> +        return generator.nextInt(1000000) % 1000000;
ㅎㅎ 자바에선 이렇게 하는군요

2023-11-26 07:29 UTC, wkdehdgk159 commented on src/main/java/com/sparta/newsfeed/user/AuthCode.java
> +    private String username;
임시적으로 쓰이는 entity이기 때문에 굳이 연관관계를 설정해 줄 필요가 있을까? 라는 고민이 있었습니다.
진훈님이 말씀해주신 문자열비교의 효율성에 대해 고민해보겠습니다.

2023-11-26 08:01 UTC, OuOHoon approved these changes

2023-11-26 08:04 UTC, merged